repos:
  - repo: https://github.com/PyCQA/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-bugbear
          - flake8-comprehensions
        args:
          - "--max-line-length=250"
          - "--ignore=E203,W503"
        files: ^app/.*\.py$

  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1
    hooks:
      - id: isort
        args:
          - "--profile=black"
          - "--line-length=250"
        files: ^app/.*\.py$

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.15.0
    hooks:
      - id: pyupgrade
        args:
          - "--py310-plus"
        files: ^app/.*\.py$

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-added-large-files
        files: ^app/.*\.py$
      - id: check-ast
        files: ^app/.*\.py$
      - id: check-docstring-first
        files: ^app/.*\.py$
      - id: check-yaml
        files: ^app/.*\.py$
      - id: end-of-file-fixer
        files: ^app/.*\.py$
      - id: trailing-whitespace
        files: ^app/.*\.py$
